# Generated by Django 4.0 on 2022-01-19 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_topic_resource'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='parent_topics',
            field=models.ManyToManyField(blank=True, related_name='child_topics', to='polls.Topic'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='prereq_topics',
            field=models.ManyToManyField(blank=True, related_name='postreq_topics', to='polls.Topic'),
        ),
    ]
