# Generated by Django 4.0 on 2022-01-19 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_alter_topic_parent_topics_alter_topic_prereq_topics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='parent_topics',
            field=models.ManyToManyField(blank=True, to='polls.Topic'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='prereq_topics',
            field=models.ManyToManyField(blank=True, to='polls.Topic'),
        ),
    ]
