# Generated by Django 4.0 on 2022-01-21 22:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_alter_topic_parent_topics_alter_topic_prereq_topics'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='parent_topics',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='prereq_topics',
        ),
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation_type', models.IntegerField(choices=[(1, 'Child Of'), (2, 'Prereq Of')])),
                ('source_topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='successor_relations', to='polls.topic')),
                ('target_topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predecessor_relations', to='polls.topic')),
            ],
        ),
    ]
