# Generated by Django 4.0 on 2022-02-02 21:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('polls', '0005_remove_topic_parent_topics_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='relationship',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
        ),
        migrations.AddField(
            model_name='relationship',
            name='weight',
            field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name='relationship',
            name='relation_type',
            field=models.IntegerField(choices=[(1, 'Child Of'), (2, 'Prereq Of'), (3, 'Knowledge Of')]),
        ),
    ]
