# Generated by Django 4.0 on 2022-02-09 21:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_relationship_user_relationship_weight_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relationship',
            name='source_topic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='successor_relations', to='polls.topic'),
        ),
    ]
