# Generated by Django 4.0 on 2022-02-16 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_alter_relationship_source_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relationship',
            name='relation_type',
            field=models.IntegerField(choices=[(1, 'Child Of'), (2, 'Prereq Of'), (3, 'Knowledge Of'), (4, 'Goal Of')]),
        ),
    ]
