# Generated by Django 4.0 on 2022-03-04 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_alter_relationship_relation_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='topic_title',
            new_name='title',
        ),
    ]
