# Generated by Django 4.0 on 2022-03-09 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_alter_relationship_relation_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resource',
            old_name='resource_link',
            new_name='link',
        ),
        migrations.RenameField(
            model_name='resource',
            old_name='resource_title',
            new_name='title',
        ),
        migrations.AddField(
            model_name='resource',
            name='votes',
            field=models.IntegerField(default=0),
        ),
    ]
