# Generated by Django 4.0 on 2022-03-11 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_rename_resource_link_resource_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='author',
            field=models.CharField(default='fart', max_length=200),
            preserve_default=False,
        ),
    ]
