# Generated by Django 4.0 on 2022-06-06 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0011_topicrelationship_topicrelvote_usergoal_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
