# Generated by Django 4.0 on 2022-06-06 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('polls', '0012_delete_choice_delete_question'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TopicRelationship',
            new_name='TopicRelation',
        ),
        migrations.RenameModel(
            old_name='TopicRelVote',
            new_name='TopicRelationVote',
        ),
    ]
