# Generated by Django 4.0 on 2022-06-06 21:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0013_rename_topicrelationship_topicrelation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='topic',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='votes',
        ),
        migrations.CreateModel(
            name='ResourceRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('votes', models.IntegerField(default=0)),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.resource')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.topic')),
            ],
        ),
    ]
